In [2]:
import numpy as np


In [184]:
            ## Working with vectors

In [3]:
a = np.array([1,2,3]) # define vectors
b = 4
a*b

array([ 4,  8, 12])

In [5]:
c = np.array([2,3,4])
a*b + c

array([ 6, 11, 16])

In [6]:
a*c

array([ 2,  6, 12])

In [7]:
a*c+3

array([ 5,  9, 15])