In [81]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

from sklearn.datasets import load_iris
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from sklearn.decomposition import PCA

# Iris-data sets and Linear SVC example

In [53]:
iris_attribute = load_iris()['data']
iris_label = load_iris()["target"]

In [54]:
iris_label

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [55]:
attribute_train,attibute_test,labels_train,labels_test = \
train_test_split(iris_attribute,iris_label)

In [56]:
svc = LinearSVC(C=1e9)

In [57]:
svc.fit(attribute_train,labels_train)

/home/daodeiv/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


LinearSVC(C=1000000000.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [59]:
print(attibute_test.shape)
print(attribute_train.shape)
svc.score(attibute_test,labels_test)

(38, 4)
(112, 4)


0.8947368421052632

In [60]:
iris_attribute = load_iris()['data']
iris_label = load_iris()["target"]
def funct_trans(x):
    if x==0:
        return 'A'
    elif x==1:
        return 'B'
    elif  x==2:
        return 'C'
        
a=pd.DataFrame(iris_label)  #.apply(funct_trans)
a.columns=['label'] 
c = a['label'].apply(funct_trans)
iris_label = c

In [61]:
attribute_train,attibute_test,labels_train,labels_test = \
train_test_split(iris_attribute,iris_label)

In [62]:
svc = LinearSVC(C=1e9)
svc.fit(attribute_train,labels_train)

/home/daodeiv/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


LinearSVC(C=1000000000.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [63]:
print(attibute_test.shape)
print(attribute_train.shape)
svc.score(attibute_test,labels_test)


(38, 4)
(112, 4)


0.9210526315789473

In [64]:
labels_test

17     A
133    C
147    C
11     A
30     A
59     B
20     A
94     B
55     B
107    C
140    C
104    C
134    C
40     A
146    C
119    C
113    C
63     B
60     B
96     B
19     A
109    C
127    C
67     B
83     B
74     B
77     B
61     B
48     A
82     B
117    C
3      A
87     B
25     A
84     B
15     A
26     A
115    C
Name: label, dtype: object

In [68]:
np.array([svc.predict(attibute_test),labels_test]).T

array([['A', 'A'],
       ['B', 'C'],
       ['C', 'C'],
       ['A', 'A'],
       ['A', 'A'],
       ['B', 'B'],
       ['A', 'A'],
       ['B', 'B'],
       ['B', 'B'],
       ['C', 'C'],
       ['C', 'C'],
       ['C', 'C'],
       ['B', 'C'],
       ['A', 'A'],
       ['C', 'C'],
       ['B', 'C'],
       ['C', 'C'],
       ['B', 'B'],
       ['B', 'B'],
       ['B', 'B'],
       ['A', 'A'],
       ['C', 'C'],
       ['C', 'C'],
       ['B', 'B'],
       ['B', 'B'],
       ['B', 'B'],
       ['B', 'B'],
       ['B', 'B'],
       ['A', 'A'],
       ['B', 'B'],
       ['C', 'C'],
       ['A', 'A'],
       ['B', 'B'],
       ['A', 'A'],
       ['B', 'B'],
       ['A', 'A'],
       ['A', 'A'],
       ['C', 'C']], dtype=object)

#### KErnel trics RAdial bases function

In [73]:
kernel_svc = SVC(kernel="rbf")

In [75]:
iris_attribute = load_iris()['data']
iris_label = load_iris()["target"]
attribute_train,attibute_test,labels_train,labels_test = \
train_test_split(iris_attribute,iris_label)

In [76]:
kernel_svc.fit(attribute_train,labels_train)

/home/daodeiv/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [77]:
kernel_svc.score(attibute_test,labels_test)

0.9736842105263158

In [78]:
np.array([kernel_svc.predict(attibute_test),labels_test]).T

array([[2, 2],
       [1, 1],
       [0, 0],
       [2, 2],
       [1, 1],
       [2, 2],
       [2, 2],
       [0, 0],
       [0, 0],
       [2, 2],
       [2, 2],
       [1, 1],
       [1, 1],
       [2, 2],
       [2, 2],
       [1, 1],
       [2, 2],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 2],
       [1, 1],
       [0, 0],
       [2, 2],
       [2, 2],
       [2, 2],
       [0, 0],
       [0, 0],
       [2, 2],
       [2, 2],
       [0, 0],
       [0, 0],
       [2, 2],
       [2, 2]])

### seee GridSearchCV( GRID SEAR FOR SVC

### LEts to apply dimensialy reduction algoritm PCA 

In [83]:
attribute_train,attibute_test,labels_train,labels_test

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [107]:
iris_attribute.shape

(150, 4)

In [108]:
iris_label.shape


(150,)

In [122]:
pca = PCA()
pca.fit(attribute_train)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [123]:
pca.explained_variance_

array([4.16546632, 0.2276385 , 0.07839593, 0.02440819])

In [124]:
tranformed_data= pca.transform(attribute_train)

In [125]:

tranformed_data.shape

(112, 4)

In [126]:
tranformed_data = tranformed_data[:,:2]
tranformed_data.shape

(112, 2)

In [118]:
kernel_svc = SVC(kernel="rbf")

In [119]:
tranformed_data.shape

(150, 2)

In [120]:
iris_label.shape

(150,)

In [127]:
kernel_svc.fit(tranformed_data,labels_train)

/home/daodeiv/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [133]:
#### TEST
attibute_test_t = pca.transform(attibute_test)[:,:2]
attibute_test_t.shape

(38, 2)

In [134]:
labels_test.shape

(38,)

In [135]:
kernel_svc.score(attibute_test_t,labels_test)

0.9473684210526315