<h2> Referecenes </h2>


https://towardsdatascience.com/adaboost-from-scratch-37a936da3d50 <br>
https://www.analyticsvidhya.com/blog/2021/09/adaboost-algorithm-a-complete-guide-for-beginners/ <br>
https://www.analyticsvidhya.com/blog/2021/09/gradient-boosting-algorithm-a-complete-guide-for-beginners/ <br>
https://towardsdatascience.com/all-you-need-to-know-about-gradient-boosting-algorithm-part-1-regression-2520a34a502

In [1]:
import numpy as np

In [22]:
def compute_alpha(error):
    '''
    Calculate the weight of a weak classifier m in the majority vote of the final classifier. This is called
    alpha in chapter 10.1 of The Elements of Statistical Learning. Arguments:
    error: error rate from weak classifier m
    '''
    return np.log((1 - error) / error)

In [2]:
def update_weights(w_i, alpha, y, y_pred):
    ''' 
    Update individual weights w_i after a boosting iteration. Arguments:
    w_i: individual weights for each observation
    y: actual target value
    y_pred: predicted value by weak classifier  
    alpha: weight of weak classifier used to estimate y_pred
    '''  
    return w_i * np.exp(alpha * (np.not_equal(y, y_pred)).astype(int))

In [5]:
y = np.array([1,0,1])
y_pred = np.array([1,1,1])

In [7]:
np.not_equal(y,y_pred).astype(int)

array([0, 1, 0])

In [14]:
y_pred = np.array([+1,-1,+1])



array([ 1, -1,  1])

In [15]:
np.sign(y_pred)

array([ 1, -1,  1])

In [20]:
erroe =(1 - 0.4)/0.4
erroe

1.4999999999999998

In [26]:
compute_alpha(0.8)

-1.3862943611198908