In [53]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd 
from sklearn.preprocessing import MinMaxScaler ##Scalling data
from sklearn.model_selection import train_test_split## sperationg data

# Tree and Esembles methods Notes

In [5]:
adult_income_data = pd.read_csv('sources/adult.csv')
adult_income_data.head(10)

age         workclass  fnlwgt     education  educational-num  \
0   25           Private  226802          11th                7   
1   38           Private   89814       HS-grad                9   
2   28         Local-gov  336951    Assoc-acdm               12   
3   44           Private  160323  Some-college               10   
4   18                 ?  103497  Some-college               10   
5   34           Private  198693          10th                6   
6   29                 ?  227026       HS-grad                9   
7   63  Self-emp-not-inc  104626   Prof-school               15   
8   24           Private  369667  Some-college               10   
9   55           Private  104996       7th-8th                4   

       marital-status         occupation   relationship   race  gender  \
0       Never-married  Machine-op-inspct      Own-child  Black    Male   
1  Married-civ-spouse    Farming-fishing        Husband  White    Male   
2  Married-civ-spouse    Protective-serv        Husband  White    Male   
3  Married-civ-spouse  Machine-op-inspct        Husband  Black    Male   
4       Never-married                  ?      Own-child  White  Female   
5       Never-married      Other-service  Not-in-family  White    Male   
6       Never-married                  ?      Unmarried  Black    Male   
7  Married-civ-spouse     Prof-specialty        Husband  White    Male   
8       Never-married      Other-service      Unmarried  White  Female   
9  Married-civ-spouse       Craft-repair        Husband  White    Male   

   capital-gain  capital-loss  hours-per-week native-country income  
0             0             0              40  United-States  <=50K  
1             0             0              50  United-States  <=50K  
2             0             0              40  United-States   >50K  
3          7688             0              40  United-States   >50K  
4             0             0              30  United-States  <=50K  
5             0             0              30  United-States  <=50K  
6             0             0              40  United-States  <=50K  
7          3103             0              32  United-States   >50K  
8             0             0              40  United-States  <=50K  
9             0             0              10  United-States  <=50K

In [11]:
#adult_income_data = adult_income_data.drop('fnlwgt',axis=1)


In [60]:
attribute = adult_income_data.drop('income',axis=1)
labels = adult_income_data['income']

In [61]:
#### checking balance of data

adult_income_data.groupby('income').size()/len(adult_income_data)

income
<=50K    0.760718
>50K     0.239282
dtype: float64

###### The is not balance floating sum does not give the 100%
###### we have to use some methods to balance it as oversampling for correctin of metric wich have
###### !!! Anomai;lie arises when one of gropued has 99 other has 1 persent

In [62]:
#### lets to get the indicator variable called dummies
attribute = pd.get_dummies(attribute)
attribute.shape

(48842, 107)

##### we have to apply scalling into data.for every columns learns tranformation,after getting learning ,the object will be able to aply for other columns


In [63]:
### the must to be between [0,1]
scaller = MinMaxScaler()
attributes =  scaller.fit_transform(attribute)
print(attributes.max(axis=1))
print(attributes.min(axis=1))
print(attributes.mean(axis=1))

[1. 1. 1. ... 1. 1. 1.]
[0. 0. 0. ... 0. 0. 0.]
[0.08324811 0.08711219 0.08674745 ... 0.08871903 0.08220284 0.08935501]


/home/daodeiv/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py:334: DataConversionWarning: Data with input dtype uint8, int64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


In [67]:
### separated data into test data and train data
attributes_test,attributes_train,label_test,label_train = train_test_split(attributes,labels,train_size=0.7,stratify=labels)

/home/daodeiv/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [79]:
(attributes_test.shape[0]/attributes_train.shape[0])/100



0.023332423394526722