In [1]:
import warnings
import datetime

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

from sklearn.model_selection import train_test_split
from IPython.display import display, Markdown , Math 

sns.set()
warnings.filterwarnings('ignore')

# Matrix

<div class='intro'> </div>
<p> In mathematics, a matrix is a rectangular array of numbers or symbols arranged in rows and columns.In history,
    a matrix was developed as a tool used for solving system linear equations.The size of matrix is defined by
    the number of columns abd rows that it contains. 
    The size of the matrix is defined by the number of columns and rows that it contains.
    The matrix with m rows and n columns is denoted by $m\times n$ which is written as n-by-m matrix.
    $$A_{m,n} = 
 \begin{pmatrix}
  a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
  a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,1} & a_{m,2} & \cdots & a_{m,n} 
 \end{pmatrix} $$
</p>

## Basic Properties
### Transpose Matrix
The transpose of a matrix is simply a flipped version of the original matrix. We can transpose a matrix by switching its rows with its columns.
We denote the transpose of matrix $A$ by $A^T$. For example, if <br> <br>
 $A_{m,n} = 
 \begin{pmatrix}
  a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
  a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,1} & a_{m,2} & \cdots & a_{m,n} 
 \end{pmatrix} $
 <br>
 
  $A = 
 \begin{pmatrix}
  a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
  a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
 \end{pmatrix} $ 
  $A^T = 
 \begin{pmatrix}
  a_{1,1} & a_{2,1}  \\
  a_{1,2} & a_{2,2} \\
  \vdots & \vdots \\
  a_{1,n} &  a_{2,n}
 \end{pmatrix} $  <br>
### Adding and Substracting
Matrix addition is comulative and associative <br> <br>
$A+B = B+A = C$
where $c_{ij}=a_{ij}+b_{ij}  $ <br>

$(A+B) + C= A + (B+C)$
### Scallar multiplication
$(\gamma+\delta)A =\gamma A + \delta B $
### Matrix multiplication 
$AB=C$ where $c_{ij} = \sum_k a_{ik}b_{kj}$ <br> <br>
propeties <br> <br>
$(AB)^T=B^TA^T$


### Matrix mutliplication is distributive <br>
$A(B+C)= AB+AC $

### Matrix mutliplication is associative
$A(BC)=(AB)C$
### Matrix multiplication is not commutative
$AB\ne BA$

### Identity matrix 
 $I = 
 \begin{pmatrix}
   1 & 0 & 0  \\
 0 & 1 & 0  \\
  0 & 0 & 1  
 \end{pmatrix} $  <br>
<br> <br>
#####  for every matrix
$IA=AI=A$ 

### Inverse Matrices
The matrix inverse of $A$ is denoted $A^{−1}$. It is the matrix that results in the identity matrix when it is multiplied by A:

$A^{-1}A=I$

## Examples with NymPY

In [2]:
A = np.array([[2, 3], [6, 5]])
A

array([[2, 3],
       [6, 5]])

In [3]:
B = np.array([[5, 3], [2, 2]])
B

array([[5, 3],
       [2, 2]])

$AB$

In [4]:
AB = np.dot(A, B)
AB

array([[16, 12],
       [40, 28]])

BA

In [11]:
BA = np.dot(B, A)
BA

array([[28, 30],
       [16, 16]])

$(AB)^T$

In [6]:
(A.dot(B)).T

array([[16, 40],
       [12, 28]])

$B^TA^T$

In [7]:
B.T.dot(A.T)

array([[16, 40],
       [12, 28]])

#### from above  we can see : 
$(AB)^T$ = $B^TA^T$

I

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

$A^{-1}$

In [12]:
A_inv = np.linalg.inv(A)
A_inv

array([[-0.625,  0.375],
       [ 0.75 , -0.25 ]])

$A^{-1}A=I$

In [10]:
np.round(A_inv.dot(A))

array([[1., 0.],
       [0., 1.]])