In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import math
from mpl_toolkits.mplot3d import Axes3D
from random import random
import pandas as pd

#Singular Value Decomposition $\land$

### SVD  factorization of a matrix into three matrices.

In [33]:
A = np.array([[1,2],[2,1]])
np.linalg.eig(A)

(array([ 3., -1.]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [6]:
1/2**(1/2)

0.7071067811865475

In [34]:
X,q = np.linalg.eig(A)

In [36]:
X
np.ones((2,2))
gamma = np.diag(X)

In [37]:
Z = q.dot(gamma).dot(q.T)

In [38]:
Z

array([[1., 2.],
       [2., 1.]])