In [39]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import math
from mpl_toolkits.mplot3d import Axes3D
from random import random
import pandas as pd


from sklearn.datasets import load_iris
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression

In [29]:
#PCA - NOTES - IRIS DATA_SETS
iris_data,iris_label = load_iris().data,load_iris().target


In [30]:
iris_data.shape
#da= pd.DataFrame(iris_data,columns=iris_label.T)

(150, 4)

In [27]:
da.head()

0    0    0    0    0    0    0    0    0    0  ...    2    2    2    2  \
0  5.1  4.9  4.7  4.6  5.0  5.4  4.6  5.0  4.4  4.9  ...  6.7  6.9  5.8  6.8   
1  3.5  3.0  3.2  3.1  3.6  3.9  3.4  3.4  2.9  3.1  ...  3.1  3.1  2.7  3.2   
2  1.4  1.4  1.3  1.5  1.4  1.7  1.4  1.5  1.4  1.5  ...  5.6  5.1  5.1  5.9   
3  0.2  0.2  0.2  0.2  0.2  0.4  0.3  0.2  0.2  0.1  ...  2.4  2.3  1.9  2.3   

     2    2    2    2    2    2  
0  6.7  6.7  6.3  6.5  6.2  5.9  
1  3.3  3.0  2.5  3.0  3.4  3.0  
2  5.7  5.2  5.0  5.2  5.4  5.1  
3  2.5  2.3  1.9  2.0  2.3  1.8  

[4 rows x 150 columns]

In [18]:
pca = PCA()
pca.fit(iris_data)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [51]:
tranformed_data= pca.transform(iris_data)

array([[-2.68412563e+00,  3.19397247e-01, -2.79148276e-02,
        -2.26243707e-03],
       [-2.71414169e+00, -1.77001225e-01, -2.10464272e-01,
        -9.90265503e-02],
       [-2.88899057e+00, -1.44949426e-01,  1.79002563e-02,
        -1.99683897e-02],
       [-2.74534286e+00, -3.18298979e-01,  3.15593736e-02,
         7.55758166e-02],
       [-2.72871654e+00,  3.26754513e-01,  9.00792406e-02,
         6.12585926e-02],
       [-2.28085963e+00,  7.41330449e-01,  1.68677658e-01,
         2.42008576e-02],
       [-2.82053775e+00, -8.94613845e-02,  2.57892158e-01,
         4.81431065e-02],
       [-2.62614497e+00,  1.63384960e-01, -2.18793179e-02,
         4.52978706e-02],
       [-2.88638273e+00, -5.78311754e-01,  2.07595703e-02,
         2.67447358e-02],
       [-2.67275580e+00, -1.13774246e-01, -1.97632725e-01,
         5.62954013e-02],
       [-2.50694709e+00,  6.45068899e-01, -7.53180094e-02,
         1.50199245e-02],
       [-2.61275523e+00,  1.47299392e-02,  1.02150260e-01,
      

In [52]:
pca.explained_variance_

array([4.22824171, 0.24267075, 0.0782095 , 0.02383509])

In [53]:
pca.explained_variance_ratio_

array([0.92461872, 0.05306648, 0.01710261, 0.00521218])

#### acording pca the first colum has a beggiest weightm,that brings the  mind  ,the whole data sets can be represents only with one column,because the firs columns has 90% accurancy,also this mean that the firs column can be represents as linear combination of other

In [54]:
tranformed_data.mean(axis=0)

array([-2.52834790e-15, -8.55241803e-16, -3.22334751e-16, -6.40598685e-16])

##### the mean values of columns is 0 because PCA make substract to evety point mean value

In [37]:
tranformed_data.std(axis=0)

array([2.04940319, 0.49097143, 0.27872586, 0.1538707 ])

the std deviation stands more and more smaller,because the pca orderd columns by its variace the os the purpose of PCA 

In [41]:
iris_atribute = tranformed_data[:,:2]
iris_atribute.shape

(150, 2)

In [47]:
iris_atribute[1].max()
iris_label  ### label remain the same ,there is no need to be tranformed with PCA

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [46]:
iris_label.shape

(150,)

In [55]:
ir_normal  = LogisticRegression(C=1e5)
ir_normal.fit(iris_data,iris_label)  ### train untraformed data


/home/daodeiv/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/daodeiv/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=100000.0, class_weight=None, dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='warn', n_jobs=None, penalty='l2', random_state=None,
          solver='warn', tol=0.0001, verbose=0, warm_start=False)

In [66]:
ir_transform =  LogisticRegression(C=1e5).fit(iris_atribute,iris_label) ## train traformed data with PCA

/home/daodeiv/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/daodeiv/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


#### Score

In [58]:
ir_normal.score(iris_data,iris_label)

0.98

### 0.98  wich verry good result  ,in original data.We do not expect the score of tranformed data to be more better ,because there are some dimensinaly reduction,be the train time must to be faster 

In [61]:
ir_transform.score(iris_atribute,iris_label)

0.9666666666666667

### 0.96 the difference is not so big 

#### The iris data sets with applied PCA ,shows us the powerful of PCA ,because we loose much data and our score is not so different wich mean ,the does not loose the the siginificat of our data

In [62]:
###@ lets to make the but with only one attribute

In [64]:
iris_atribute = tranformed_data[:,:2]

print(iris_atribute.shape)
iris_atribute = tranformed_data[:,:1]

print(iris_atribute.shape)
iris_atribute = tranformed_data[:,:1].reshape(,)

print(iris_atribute.shape)

(150, 2)
(150, 1)


In [67]:
ir_transform =  LogisticRegression(C=1e5).fit(iris_atribute,iris_label) 

/home/daodeiv/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/daodeiv/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [68]:
ir_transform.score(iris_atribute,iris_label)

0.94

### The new score is 94% we lose 4 % but we reduce the data 4 times,the new data is 4 times ,more less

#### what we achive with pca 
[1] the data is more less <br>
[2] removed linead dependes values wich does bring sence in our fiitinf<br>
[23]COlumns with large values is realiy dominate the other (variace_ration)<br>
[removed] corelation columns<br>
[removed] the last columns with smalest variance (variance ration)
we remove the uncesary noice---THis make a regularazation<br> 

In [ ]:
KErnel PCA