In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler

In [2]:
x = np.random.normal(0, 1, 500)
y = np.random.normal(0, 1, 500)
X = np.vstack((x, y)).T

In [18]:
X = np.array([ [1,3,4],
               [3,5,5],
               [4,5,3]])

cov = np.cov(X.T)

In [19]:
eigen_values , V = np.linalg.eigh(cov)
print("eigen values : " , eigen_values.T)
print("eigen vectors stacked V : " )
print(V)

eigen values :  [2.21177243e-16 1.03162505e+00 3.63504161e+00]
eigen vectors stacked V : 
[[-0.59628479 -0.05960415 -0.80055717]
 [ 0.74535599  0.32925926 -0.57968335]
 [-0.2981424   0.94235645  0.15190598]]


In [35]:
w , v = np.linalg.eigh(cov)  #eigenvalues and eigenvectors of a real symmetric or complex Hermitian (conjugate symmetric) array.

idx = np.argsort(w)
print(idx)
idx = idx[:w.size]
print(idx)
w = w[idx]
v = v[:,idx]
np.flip(v, axis=1)

[0 1 2]
[0 1 2]


array([[-0.80055717, -0.05960415, -0.59628479],
       [-0.57968335,  0.32925926,  0.74535599],
       [ 0.15190598,  0.94235645, -0.2981424 ]])

In [16]:
np.flipud(V,axis=1)

TypeError: _flip_dispatcher() got an unexpected keyword argument 'axis'